import { redirect } from "next/navigation";
import { Activity, BarChart3, Sparkles } from "lucide-react";
import { getCurrentUser } from "@/lib/session";
// import { DeepSeekIcon } from "@/components/deepseek-icon";
import { HealthIndicator } from "@/components/dashboard/health-indicator";
import { UserMenu } from "@/components/dashboard/user-menu";
import { Logo } from "@/components/logo";

const highlights = [
  {
    icon: Sparkles,
    title: "AI-powered analysis",
    description: "Event summaries generated by the DeepSeek model.",
  },
  {
    icon: BarChart3,
    title: "Real-time events",
    description: "Track and queue product events as they arrive.",
  },
  {
    icon: Activity,
    title: "Backend health",
    description: "Monitor Redis connectivity from the header at a glance.",
  },
];

export default async function DashboardPage() {
  const user = await getCurrentUser();
  if (!user) redirect("/login");

  return (
    <main className="min-h-screen bg-zinc-50">
      <header className="border-b border-zinc-200 bg-white">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-2 px-4 py-4 sm:gap-3 sm:px-6 lg:px-8 lg:py-5">
          <Logo />

          <div className="flex items-center gap-2 sm:gap-3">
            <div className="flex flex-col items-center gap-1">
              <HealthIndicator />
              {/*<DeepSeekIcon className="h-4 w-4 animate-pulse" />*/}
            </div>
            <UserMenu email={user.email} />
          </div>
        </div>
      </header>

      <section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
        <div className="relative overflow-hidden rounded-2xl bg-linear-to-br from-indigo-600 via-violet-600 to-fuchsia-600 p-8 text-white shadow-lg sm:p-10">
          <div className="pointer-events-none absolute -right-16 -top-16 h-64 w-64 rounded-full bg-white/10 blur-2xl" />
          <div className="pointer-events-none absolute -bottom-24 -left-10 h-72 w-72 rounded-full bg-white/10 blur-3xl" />

          <div className="relative">
            <p className="text-sm font-medium text-indigo-100">Overview</p>
            <h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">
              Welcome back, {user.email}
            </h1>
            <p className="mt-3 max-w-2xl text-sm text-indigo-100">
              Monitor events, review AI-powered analyses, and keep an eye on
              your backend health — all in one place.
            </p>
          </div>
        </div>

        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {highlights.map(({ icon: Icon, title, description }) => (
            <div
              key={title}
              className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"
            >
              <span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-linear-to-br from-indigo-500 to-violet-500 text-white">
                <Icon className="h-5 w-5" />
              </span>
              <h2 className="mt-4 text-sm font-semibold text-zinc-900">
                {title}
              </h2>
              <p className="mt-1 text-sm text-zinc-500">{description}</p>
            </div>
          ))}
        </div>
      </section>
    </main>
  );
}
